[2025-04-06 08:03:38,427] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_inference_pipeline.checking_model_prediction_ratio manual__2025-04-06T08:02:57.498516+00:00 [queued]>
[2025-04-06 08:03:38,432] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_inference_pipeline.checking_model_prediction_ratio manual__2025-04-06T08:02:57.498516+00:00 [queued]>
[2025-04-06 08:03:38,432] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-04-06 08:03:38,432] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2025-04-06 08:03:38,432] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-04-06 08:03:38,451] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): checking_model_prediction_ratio> on 2025-04-06 08:02:57.498516+00:00
[2025-04-06 08:03:38,456] {standard_task_runner.py:52} INFO - Started process 15026 to run task
[2025-04-06 08:03:38,460] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_inference_pipeline', 'checking_model_prediction_ratio', 'manual__2025-04-06T08:02:57.498516+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_inference_pipeline/.ipynb_checkpoints/lead_scoring_inference_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmptq09owb8', '--error-file', '/tmp/tmptq0aaqwh']
[2025-04-06 08:03:38,461] {standard_task_runner.py:80} INFO - Job 52: Subtask checking_model_prediction_ratio
[2025-04-06 08:03:38,504] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_inference_pipeline.checking_model_prediction_ratio manual__2025-04-06T08:02:57.498516+00:00 [running]> on host c6537eab7989
[2025-04-06 08:03:38,652] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_inference_pipeline
AIRFLOW_CTX_TASK_ID=checking_model_prediction_ratio
AIRFLOW_CTX_EXECUTION_DATE=2025-04-06T08:02:57.498516+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-06T08:02:57.498516+00:00
[2025-04-06 08:03:42,632] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mlopsAssignment/Airflow/Dags/Lead_scoring_inference_pipeline/utils.py", line 155, in prediction_ratio_check
    with open(FILE_PATH+'prediction_distribution.txt', 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/dags/Lead_scoring_inference_pipeline/prediction_distribution.txt'
[2025-04-06 08:03:42,635] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=Lead_scoring_inference_pipeline, task_id=checking_model_prediction_ratio, execution_date=20250406T080257, start_date=20250406T080338, end_date=20250406T080342
[2025-04-06 08:03:42,655] {standard_task_runner.py:92} ERROR - Failed to execute job 52 for task checking_model_prediction_ratio ([Errno 2] No such file or directory: '/home/airflow/dags/Lead_scoring_inference_pipeline/prediction_distribution.txt'; 15026)
[2025-04-06 08:03:42,686] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-04-06 08:03:42,727] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
