[2025-04-06 08:00:04,147] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_inference_pipeline.encoding_categorical_variables scheduled__2025-04-06T07:00:00+00:00 [queued]>
[2025-04-06 08:00:04,152] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_inference_pipeline.encoding_categorical_variables scheduled__2025-04-06T07:00:00+00:00 [queued]>
[2025-04-06 08:00:04,152] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-04-06 08:00:04,152] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-04-06 08:00:04,152] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-04-06 08:00:04,173] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): encoding_categorical_variables> on 2025-04-06 07:00:00+00:00
[2025-04-06 08:00:04,178] {standard_task_runner.py:52} INFO - Started process 14559 to run task
[2025-04-06 08:00:04,181] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_inference_pipeline', 'encoding_categorical_variables', 'scheduled__2025-04-06T07:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_inference_pipeline/.ipynb_checkpoints/lead_scoring_inference_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmp9c6vw9c1', '--error-file', '/tmp/tmpjdmdr0g5']
[2025-04-06 08:00:04,181] {standard_task_runner.py:80} INFO - Job 46: Subtask encoding_categorical_variables
[2025-04-06 08:00:04,222] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_inference_pipeline.encoding_categorical_variables scheduled__2025-04-06T07:00:00+00:00 [running]> on host c6537eab7989
[2025-04-06 08:00:04,379] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_inference_pipeline
AIRFLOW_CTX_TASK_ID=encoding_categorical_variables
AIRFLOW_CTX_EXECUTION_DATE=2025-04-06T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-04-06T07:00:00+00:00
[2025-04-06 08:00:04,380] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mlopsAssignment/Airflow/Dags/Lead_scoring_inference_pipeline/utils.py", line 49, in encode_features
    conn = sqlite3.connect(DB_PATH+DB_FILE_NAME)
sqlite3.OperationalError: unable to open database file
[2025-04-06 08:00:04,382] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_scoring_inference_pipeline, task_id=encoding_categorical_variables, execution_date=20250406T070000, start_date=20250406T080004, end_date=20250406T080004
[2025-04-06 08:00:04,399] {standard_task_runner.py:92} ERROR - Failed to execute job 46 for task encoding_categorical_variables (unable to open database file; 14559)
[2025-04-06 08:00:04,433] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-04-06 08:00:04,485] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
