[2025-04-06 06:35:43,951] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-04-06 06:35:43,955] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-04-06 06:35:43,955] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-04-06 06:35:43,956] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-04-06 06:35:43,956] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-04-06 06:35:43,976] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): encoding_categorical_variables> on 2025-03-01 00:00:00+00:00
[2025-04-06 06:35:43,986] {standard_task_runner.py:52} INFO - Started process 1816 to run task
[2025-04-06 06:35:43,990] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_training_pipeline', 'encoding_categorical_variables', 'scheduled__2025-03-01T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_training_pipeline/.ipynb_checkpoints/lead_scoring_training_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmprfflxl3v', '--error-file', '/tmp/tmp37u8q_79']
[2025-04-06 06:35:43,990] {standard_task_runner.py:80} INFO - Job 25: Subtask encoding_categorical_variables
[2025-04-06 06:35:44,034] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables scheduled__2025-03-01T00:00:00+00:00 [running]> on host c6537eab7989
[2025-04-06 06:35:44,086] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_training_pipeline
AIRFLOW_CTX_TASK_ID=encoding_categorical_variables
AIRFLOW_CTX_EXECUTION_DATE=2025-03-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-01T00:00:00+00:00
[2025-04-06 06:35:44,087] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mlopsAssignment/Airflow/Dags/Lead_scoring_training_pipeline/utils.py", line 58, in encode_features
    conn = sqlite3.connect(DB_PATH+DB_FILE_NAME)
sqlite3.OperationalError: unable to open database file
[2025-04-06 06:35:44,090] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_scoring_training_pipeline, task_id=encoding_categorical_variables, execution_date=20250301T000000, start_date=20250406T063543, end_date=20250406T063544
[2025-04-06 06:35:44,108] {standard_task_runner.py:92} ERROR - Failed to execute job 25 for task encoding_categorical_variables (unable to open database file; 1816)
[2025-04-06 06:35:44,121] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-04-06 06:35:44,152] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
